version: "3.8"

services:
  veilwatch_db:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: veilwatch
      MARIADB_USER: veilwatch
      MARIADB_PASSWORD: veilwatch_pw
      MARIADB_ROOT_PASSWORD: root_change_me
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - veilwatch_db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    ports:
      - "3406:3306"

  veilwatch_app:
    build:
      context: ./api
    restart: unless-stopped
    environment:
      PORT: "8080"
      MYSQL_HOST: "veilwatch_db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "veilwatch"
      MYSQL_USER: "veilwatch"
      MYSQL_PASSWORD: "veilwatch_pw"
      VEILWATCH_DM_KEY: "VEILWATCHDM"
    depends_on:
      - veilwatch_db
    ports:
      - "8099:8080"
    volumes:
      - veilwatch_app_data:/app/data

  veilwatch_phpmyadmin:
    image: phpmyadmin:5-apache
    restart: unless-stopped
    environment:
      PMA_HOST: veilwatch_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    depends_on:
      - veilwatch_db
    ports:
      - "8282:80"

volumes:
  veilwatch_db_data: {}
  veilwatch_app_data: {}
