CREATE TABLE IF NOT EXISTS vw_state (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  state_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vw_users (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  username VARCHAR(32) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(16) NOT NULL DEFAULT 'player',
  temp_password VARCHAR(255) DEFAULT NULL,
  must_change_password TINYINT(1) NOT NULL DEFAULT 0,
  active_char_id VARCHAR(64) DEFAULT NULL,
  created_at BIGINT NOT NULL,
  INDEX idx_vw_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS vw_inventory_items (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  category VARCHAR(64) NOT NULL DEFAULT 'Misc',
  default_weight VARCHAR(32) DEFAULT NULL,
  default_cost DECIMAL(10,2) DEFAULT NULL,
  default_notes TEXT DEFAULT NULL,
  ammo_type VARCHAR(64) DEFAULT NULL,
  default_qty INT NOT NULL DEFAULT 1,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_vw_inventory_items_category (category),
  INDEX idx_vw_inventory_items_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vw_inventory_items_custom (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  category VARCHAR(64) NOT NULL DEFAULT 'Misc',
  default_weight VARCHAR(32) DEFAULT NULL,
  default_cost DECIMAL(10,2) DEFAULT NULL,
  default_notes TEXT DEFAULT NULL,
  ammo_type VARCHAR(64) DEFAULT NULL,
  default_qty INT NOT NULL DEFAULT 1,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_by VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_vw_inventory_items_custom_category (category),
  INDEX idx_vw_inventory_items_custom_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
