CREATE TABLE IF NOT EXISTS vw_state (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  state_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vw_users (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  username VARCHAR(32) NOT NULL UNIQUE,
  role VARCHAR(16) NOT NULL,
  pass_algo VARCHAR(32) NOT NULL,
  pass_salt CHAR(32) NOT NULL,
  pass_hash CHAR(128) NOT NULL,
  active_char_id VARCHAR(64) NULL,
  created_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
